Add config flags
itmo153277/vpnes pull request #6
Opened 2018-05-27 16:53 UTC by arhont375

Add ability to pass options by using flags on executable.

Haven't tested on windows

2018-06-03 05:00 UTC, itmo153277 requested changes
Your formatting is wrong. Use `clang-format` with the config provided in the repo.

Update travis-ci and appveyor scripts to fix the pipelines.

2018-06-03 05:00 UTC, itmo153277 commented on .gitignore
> +/Tests
You don't need to edit `.gitignore`, just build it in a different directory (or use one of the specified sub-directories: `Debug` or `Release`).

The list you provided does not cover all the files generated by autotools anyway.

2018-06-03 05:00 UTC, itmo153277 commented on Makefile.am
> +	src/config/config.cpp
Any reason to build this file twice? It is already included in `libcore.a`, and tester does link against it, so why it is listed here?

2018-06-03 05:00 UTC, itmo153277 commented on Makefile.am
> +	include/vpnes/config/config.hpp \
List it in alphabetical order

2018-06-03 05:00 UTC, itmo153277 commented on Makefile.am
> +vpnes_CPPFLAGS = $(AM_CPPFLAGS) $(SDL_CFLAGS) $(BOOST_CPPFLAGS) $(BOOST_PROGRAM_OPTIONS_CPPFLAGS)
There is no `BOOST_PROGRAM_OPTIONS_CPPFLAGS`, is there?

2018-06-03 05:00 UTC, itmo153277 commented on Makefile.am
> +tester_blargg_CPPFLAGS = $(AM_CPPFLAGS) $(SDL_CFLAGS) $(BOOST_CPPFLAGS) $(BOOST_PROGRAM_OPTIONS_CPPFLAGS)
Same, no `BOOST_PROGRAM_OPTIONS_CPPFLAGS`

2018-06-03 05:00 UTC, itmo153277 commented on README.md
> +1. Boost (>=1.65)
Change it to the actual numbers so it can be read in any text viewer without rendering

2018-06-03 05:00 UTC, itmo153277 commented on config.h
> +/* config.h.  Generated from config.h.in by configure.  */
This file is specific to your platform and should not be committed

2018-06-03 05:00 UTC, itmo153277 commented on configure.ac
> +AX_BOOST_PROGRAM_OPTIONS
You might need to check `BOOST_PROGRAM_OPTIONS_LIB` after this

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/config.hpp
> +namespace po = boost::program_options;
Do not define it like this in header files. If you really want or can't avoid defining an alias, do it inside an internal namespace

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/config.hpp
> +	SCoreConfig m_coreConfig;
This architecture is flawed. `SGuiConfig` might need to notify `CGUI` if some of the parameters were changed. It is not clear how it should be implemented in the current structure.

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/config.hpp
> +	po::options_description defineCMDOptions();
Was this function supposed to be `virtual`? If not, why it is in `protected` scope?
If this class is not going to be inherited, don't use virtual dtors

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/config.hpp
> +	SGuiConfig& getGuiConfig() {
If `SGuiConfig` is not supposed to be changed, return `const SGuiConfig&`, otherwise return `SGuiConfig*` to avoid confusion.

If it is a copy, return `SGuiConfig`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/config.hpp
> +	SCoreConfig& getCoreConfig() {
Same as above, change to `const SCoreConfig &` , `SCoreConfig` or `SCoreConfig *`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/core.hpp
> +#include <string>
If you do not use `fstream` or `string` , do not include it

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/core.hpp
> +struct SCoreConfig {
Add documentation

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/core.hpp
> +    SCoreConfig() {
Add documentation

There is no point in defining an empty ctor. This structure would have one trivial one anyway.

If you want to define a ctor with the default behaviour, use `default` keyword.

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> + * Config gor GUI
Typo?

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> +#include <string>
You do not seem to use `fstream` or `string`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> +    SGuiConfig() {
This ctor does not initialize the class members

If you are using default ctor, define it as `default`.

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> +struct SGuiConfig {
Add documentation

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> +struct SGuiConfig {
Rename to `SGUIConfig`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> +    int m_width;
Rename to `m_Width`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> +    int m_height;
Rename to `m_Height`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> +      m_width = width;
Use member ctor list instead of assignment

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> +    int getWidth() {
This function should be `const`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/gui.hpp
> +    int getHeight() {
Same, the function should be `const`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/core/config.hpp
> +#include <vpnes/config/core.hpp>
Put core config before `vpnes/core/*`

2018-06-03 05:00 UTC, itmo153277 commented on main.cpp
> +#include <vpnes/config/config.hpp>
Put config before `vpnes/gui/*`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/config.hpp
> +	bool parseOptions(int argc, char **argv);
Add doc for returning value

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/config.hpp
> +	std::string m_inputFile;
Rename to `m_InputFile`

2018-06-03 05:00 UTC, itmo153277 commented on include/vpnes/config/config.hpp
> +	std::string m_configFile;
Rename to `m_ConfigFile`

2018-06-03 05:00 UTC, itmo153277 commented on main.cpp
> +		return EXIT_FAILURE;
`EXIT_FAILURE` is defined in `cstdlib`. Include it directly to avoid confusion

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +	po::positional_options_description rom;
This naming is misleading

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +	rom.add("rom", 1);
Why not `-1`?

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +	} catch (std::exception& e) {
Catch only specific types of exceptions and propagate the other types

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +	if (variables_map.count("version")) {
Use `> 0` or `!= 0` instead of indirect conditions

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +	} else if (variables_map.count("help") || m_inputFile.empty()) {
Use `> 0` or `!= 0` instead of indirect conditions

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +		std::cout << e.what() << "\n";
Output such logs to `std::clog` or `std::cerr`

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +	po::positional_options_description rom;
This variable is unused

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +		("rom",
The help command will output `--rom` if you implement it like this, avoid it

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +void printUsage(std::ostream& out,
Use private static/non-static function instead of defining it in global namespace

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +void printUsage(std::ostream& out,
Why do you pass stream if the function is only used with `cout`?

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +	out << options;
Use `std::endl` or `std::flush` at the and

2018-06-03 05:00 UTC, itmo153277 commented on src/config/config.cpp
> +		std::cout << e.what() << "\n";
Use `std::endl` instead of `\n`

2018-06-03 05:00 UTC, itmo153277 commented on src/tests/end2end/end2end.cpp
> +struct SConfig : vpnes::config::SApplicationConfig {
This class is supposed to define some options for testing. It doesn't seem to be implemented

2018-06-03 05:00 UTC, itmo153277 commented on main.cpp
> +#include <boost/program_options.hpp>
Please include headers in this order:
1. C++ C libraries
2. C++ libraries
3. 3rd-party libraries
4. `vpnes` libraries

General headers should come first, specific ones should be at the end

2018-06-03 05:00 UTC, itmo153277 commented on Makefile.am
> +libcore_a_SOURCES = $(CORE_SOURCES) $(CONFIG_SOURCES)
With these changes `libcore.a` would require boost cpp flags

2018-06-03 05:00 UTC, itmo153277 commented on Makefile.am
> +vpnes_LDADD = $(SDL_LIBS) $(BOOST_LDFLAGS) $(BOOST_PROGRAM_OPTIONS_LIB) libcore.a
`libcore.a` depends on `-lboost_program_options`, so the order is wrong

2018-06-03 05:00 UTC, itmo153277 commented on Makefile.am
> +tester_blargg_LDADD = $(SDL_LIBS) $(BOOST_LDFLAGS) $(BOOST_PROGRAM_OPTIONS_LIB) libcore.a
Same as above, `libcore.a` depends on `-lboost_program_options`, so the order is wrong

2018-06-03 05:00 UTC, itmo153277 commented on Makefile.am
> +tester_blargg_CPPFLAGS = $(AM_CPPFLAGS) $(SDL_CFLAGS) $(BOOST_CPPFLAGS) $(BOOST_PROGRAM_OPTIONS_CPPFLAGS)
Including `SDL` to `tester_blargg` will cause build failure in mingw

2020-07-09 01:07 UTC, arhont375 commented
Closing this as makefiles is a garbage 😢

2020-07-09 01:07 UTC, closed without merging